config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "pages#home"
  root "lists#index"
  resources :lists, only: [:index, :new, :show, :create, :destroy] do
    resources :bookmarks, only: :create
  end
  resources :bookmarks, only: :destroy

  # get "lists", to: "lists#index"
  # get "lists/new", to: "lists#new"
  # get "lists/:id", to: "lists#show", as: :list
  # post "lists", to: "lists#create"
  # get "lists/:id/bookmarks/new", to: "bookmarks#new", as: :bookmarks_new
  # post "lists/:id/bookmarks", to: "bookmarks#create", as: :bookmarks
  # delete "bookmarks/:id", to: "bookmarks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  # belongs_to :user
  validates :movie, uniqueness: {scope: :list,
  message: "pair movie/list should have a unique name"}
  validates :comment, length: { minimum: 6 }
  validates :comment, length: { maximum: 50 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: { scope: :user }
  has_one_attached :photo
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend Devise::Models

  has_many :bookmarks, through: :lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow list approach
  after_action  :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  #Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    root_path
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only:[:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = Bookmark.new
    # @list = List.find(params[:list_id])
    authorize @bookmark
  end



  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # @bookmark.list.user = current_user
    # raise
    authorize @bookmark
    # raise
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # @list.user = current_user
    authorize @bookmark
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    # @lists = List.all
    @lists = policy_scope(List)
  end

  def show
    @bookmark = Bookmark.new
    # authorize @list
    # authorize @bookmark
    authorize @list

  end

  def new
    @list = List.new
    authorize @list
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    authorize @list
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @list
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def home
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<%# <div class="collapse" id="hello" role="button"> %>

  <%= render "shared/form" do %>
    <h3 class="text-center">Create a new movie</h3>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%# <%= f.association :movie, as: :select, input_html: { "data-controller" => "tom-select" } %>
      <%= f.association :movie, prompt: "Select a movie", input_html: { data: { controller: 'tom-select' } } %>
      <%= f.button :submit %>
    <% end %>
  <% end %>

<%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" if user_signed_in? %>
    <%= render "shared/container_app" if user_signed_in? %>
    <%= yield %>


    <%= render "shared/footer" if user_signed_in? %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style=" padding: 250px 0; background-image: url(<%= image_url("cinema.jpg") %>);">

  <h1 style="color: white"><span data-controller="typed-js"></span></h1>
</div>

<%= link_to "Create a movie list", new_list_path(@list), class: "btn btn-outline-dark rounded-2 float-end my-4 me-4" %>


<h2 class="text-center my-5 mx-5">🎬 My lists</h2>

<div class="list-card-container my-5">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>


      <div class="list-card" data-controller="aos" data-aos="zoom-out-up" style="background-image: url(
        <% if list.photo.key.present? %>
          <%= cl_image_path list.photo.key %>
        <% else %>
          <%= image_url("card.jpg") %>
        <% end %>
        );">
        <h3><%= list.name %></h3>
      </div>


    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render "shared/form" do %>
  <h3 class="text-center">Create a new list</h3>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, placeholder: 'Drama' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-flat' %>
  <% end %>
<% end %>

app/views/lists/show.html.erb
<div class="container my-5">

  <% if @list.movies.empty? %>
    <%= link_to "Delete list", list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Delete #{@list.name} list?" }, class: "btn btn-outline-danger my-3" if policy(@list).destroy? %>
    <%= image_tag(("box.png"), class: "img-muted") %>
    <div class="text-center">

      <h2>You have not saved any movies yet!</h2>
      <button type="button" class="btn btn-outline-dark my-4 mx-5" data-bs-toggle="modal" data-bs-target="#moviesModal">
      Add a movie
      </button>

      <%= render "shared/movie_modal" %>    </div>

  <% else %>

    <div class="banner position-relative" style="padding: 160px 0; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
    url(
        <% if @list.photo.key.present? %>
          <%= cl_image_path @list.photo.key %>
        <% else %>
          <%= image_url("card.jpg") %>
        <% end %>
      )">
      <span class="badge text-bg-dark p-2 position-absolute top-0 start-0" style="border-radius: 4px;"><strong><%= pluralize(@list.movies.count, "movie") %></strong></span>

      <h1 class="text-center"><%= @list.name %></h1>
    </div>
    <%# <br> %>
    <%# <br> %>

    <%= link_to "Delete list", list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Delete #{@list.name} list?" },
     class: "btn btn-outline-danger my-4 mx-5" if policy(@list).destroy? %>

    <%# <%= link_to "Delete list", list_path(@list), data: { turbo_method: :delete, turbo_frame: "delete_modal" },
    class: "btn btn-outline-danger my-4 mx-5" %>



    <button type="button" class="btn btn-outline-dark my-4 mx-5 float-end" data-bs-toggle="modal" data-bs-target="#moviesModal">
    Add a movie
    </button>

    <%= render "shared/movie_modal" %>
    <%# <%= link_to "Add a movie", list_path(@list), class: "btn btn-outline-dark m-2 float-end", %>
        <%# data: { 'bs-toggle':"modal", 'bs-target':"#new_movie_modal" } %>

    <%# <br> %>
    <div class="container-bookmark my-2 mx-4">
      <% @list.movies.each do |movie| %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="card-movie">
          <%= image_tag(movie.poster_url, size: "300x200") %>
          <div class="card--movie--content">
            <h3 class="text-center"><%= movie.title %></h3>
            <p><%= movie.overview %></p>
            <div class="d-flex justify-content-between">
              <div class="text-break" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis">
                <i class="fas fa-quote-left me-2"></i><small><%= bookmark.comment =%></small><i class="fas fa-quote-right ms-2"></i>
              </div>
              <div class="danger-button border-0 mx-3">
                <%= link_to "Delete", bookmark_path(bookmark),
                  data: {turbo_method: :delete, turbo_confirm: "Delete this film?"} if policy(@list).destroy? %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <% end %>



</div>

app/views/shared/_background-movies.html.erb
<%# <div style="height: 100%"> %>
  <div class="background-movies" style= "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("movies.jpg") %>);">
    <%= yield %>
  </div>
<%# </div> %>

app/views/shared/_container_app.html.erb
<div class="container-app">
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="card-footer text-muted ">


  <p class="text-center">App created by Pilar Sanchez. Data provided for free by TMDB.
  <a href="https://www.themoviedb.org/documentation/api/terms-of-use">View TMDB's terms of use</a></p>


</div>

app/views/shared/_form.html.erb
<div class="container py-5">
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_movie_modal.html.erb
<div class="modal fade" id="moviesModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create a new movie</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <div class="modal-body">
          <%= f.input :comment %>
          <%= f.association :movie, prompt: "Select a movie", input_html: { data: { controller: 'tom-select' } } %>
          <div class="modal-footer">
            <%= f.submit "Submit movie", class: "btn btn-outline-success" %>
            <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Cancel</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= image_tag("popcorn.png", class: "navbar--img")%>
  <div class="d-flex ">
    <%= link_to "My lists", lists_path, class: "btn btn-outline-dark rounded-2"  %>
      <%# <button type="button" class="btn btn-outline-dark rounded-2">My lists</button> %>
    <%# <% end %>
    <%= link_to "New list", new_list_path, class: "btn btn-outline-dark rounded-2 mx-2" %>
      <%# <button type="button" class="btn btn-outline-dark rounded-2 mx-2">New list</button> %>
    <%# <% end %>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-outline-dark" %>
    <% end %>

  </div>
</div>